select 
distinct NAME_MASTER.id_num,
NAME_MASTER.FIRST_NAME + ' '+NAME_MASTER.LAST_NAME "Name",
CANDIDACY.STAGE,
ADDRESS_MASTER.PHONE,
Address_master.ADDR_LINE_1,
ADDRESS_MASTER.CITY,
ADDRESS_MASTER.STATE,
ADDRESS_MASTER.ZIP

from CANDIDACY left JOIN NAME_MASTER on 
CANDIDACY.ID_NUM=NAME_MASTER.ID_NUM
join ADDRESS_MASTER on 
CANDIDACY.ID_NUM=ADDRESS_MASTER.ID_NUM
where CANDIDACY.YR_CDE='2016'
and CANDIDACY.TRM_CDE='20'
and ADDRESS_MASTER.ADDR_CDE 
like '*LHP'